
<html>
<body>

<table>
    <tr>
        <td>Traceback (most recent call last):<br/>  File "/Users/lamter/workspace/OpenSource/web.py-skeleton/skeleton/www/app/controllers/main_handler.py", line 58, in GET<br/>    views = Views(user)<br/>  File "/Users/lamter/workspace/OpenSource/web.py-skeleton/skeleton/www/app/models/views.py", line 23, in __init__<br/>    raise ValueError(u'模板需要一个用户对象self.user')<br/>ValueError: 模板需要一个用户对象self.user<br/></td>
    </tr>
</table>

</body>
</html>
